# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f83029272cdd8f3eda7d9aa5131dae96c8c601962e9053bd4dac001555474505b730e2acf85b9e77842c51792f79e7a30292046344d7b1d1abc6de05faeba612

test:
  secret_key_base: a37ca0b1a6b36237196d3b8d0cc085e5e8f1f98ba8e04dbf3cc8654c3a778fd428472b92bda01ab658288c63f480450af90c028ee7f884666fe08b713725f2af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
